org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

devauth.enabled=false

mod.version=1.0.1
mod.group=io.github.pingisfun
mod.id=hitboxplus
mod.name=HitBox+
mod.description=A client-side Fabric mod for customizing entity hitbox colors.

deps.fabric_loader=0.18.5
