name: Build

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle

      - name: Build and run tests
        run: ./gradlew build
